name: databaseodev
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  awesome_dialog: ^3.0.2
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_inset_box_shadow: ^1.0.8
  flutter_svg: ^2.0.4
  go_router: ^6.5.3
  google_fonts: ^4.0.3
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  intl_phone_field: ^3.1.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  overlay_support: ^2.1.0
  provider: ^6.0.5
  quickalert: ^1.0.1
  syncfusion_flutter_charts: ^21.1.38

dev_dependencies:
  build_runner: ^2.3.3

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.5
  json_serializable: ^6.6.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - bg-images/
  # - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
