name: market_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^6.2.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  custom_navigation_bar: ^0.8.2
  syncfusion_flutter_charts: ^21.1.39
  syncfusion_flutter_datepicker: ^21.1.39
  connectivity_plus: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.0.5
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/947089.jpg
    - assets/images/New.jpg
    - assets/images/Ist.jpg

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
